# This pipeline is not tested as it needs parallelism for which the form is submitted but as it states on the form which can take several days.
# Hence it is not feasible to setup the deployment pipeline at this stage considering the time constraints

# develop branch is for Develop/Test environment
# acceptance branch is for Acceptance environment
# master is for Production

trigger:
  branches:
    include:
      - develop
      - acceptance
      - master
      - feature/*

variables:
  - name: environment
    value: $(Build.SourceBranchName)

stages:
  - stage: CI
    condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'IndividualCI'))
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'


          # ✅ Remove old CLI if preinstalled
          - script: |
              pip uninstall -y databricks-cli || true
            displayName: Remove old Databricks CLI

          # ✅ Install NEW Databricks CLI (CORRECT WAY)
          - script: |
              curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash

              # Add to PATH explicitly
              export PATH=$HOME/.databricks/bin:$PATH

              # Verify version
              databricks version
            displayName: Install New Databricks CLI

          - script: databricks bundle build -t $(environment)
            displayName: 'Build Databricks Asset Bundle'
          - script: pip install -r requirements.txt
            displayName: 'Install Python Packages from requirements.txt'
          - script: pytest tests/
            displayName: 'Run Unit Tests'
  - stage: Deploy
    jobs:
      - job: DeployDatabricksBundle
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
          - script: pip install databricks-cli==0.292.0
            displayName: 'Install Databricks CLI'
          - script: |
              echo "[DEFAULT]" > ~/.databrickscfg
              echo "host = $(DATABRICKS-HOST)" >> ~/.databrickscfg
              echo "auth_type = databricks-cli" >> ~/.databrickscfg
              echo "token = $(DATABRICKS-TOKEN)" >> ~/.databrickscfg
              databricks bundle deploy --profile DEFAULT -t $(environment)
            displayName: 'Deploy Databricks Asset Bundle'