# This pipeline is not tested as it needs parallelism for which the form is submitted but as it states on the form which can take several days.
# Hence it is not feasible to setup the deployment pipeline at this stage considering the time constraints

# develop branch is for Develop/Test environment
# acceptance branch is for Acceptance environment
# master is for Production

trigger:
  branches:
    include:
      - develop
      - acceptance
      - master
      - feature/*

variables:
  - name: environment
    value: $(Build.SourceBranchName)
  - name: DATABRICKS_HOST
    value: https://adb-7405615066465253.13.azuredatabricks.net/
  - name: DATABRICKS-TOKEN
    value: "<REMOVED_ToBeAdded>"
  

stages:
  - stage: CI
    condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'IndividualCI'))
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'


          # Remove old CLI if preinstalled
          - script: |
              pip uninstall -y databricks-cli || true
            displayName: Remove old Databricks CLI

          # Install NEW Databricks CLI
          - script: |
              curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash

              # Add to PATH explicitly
              export PATH=$HOME/.databricks/bin:$PATH

              # Verify version
              databricks version
            displayName: Install New Databricks CLI

          - script: databricks bundle build -t $(environment)
            displayName: 'Build Databricks Asset Bundle'
          - script: pip install -r requirements.txt
            displayName: 'Install Python Packages and tools'
          - script: pip install pre-commit
            displayName: 'Install pre-commit'          
          - script: pip install uv
            displayName: 'Install uv'
          - script: pre-commit run --all-files
            displayName: 'Run pre-commit hooks'
          - script: export PYTHONPATH=$(pwd) && pytest tests/
            displayName: 'Run Unit Tests'
  - stage: Deploy
    jobs:
      - job: DeployDatabricksBundle
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
          - script: |
              # Install Databricks CLI
              curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash
              export PATH=$HOME/.databricks/bin:$PATH
              databricks version

              # Configure Databricks CLI
              echo "[DEFAULT]" > ~/.databrickscfg
              echo "host = $(DATABRICKS_HOST)" >> ~/.databrickscfg
              echo "auth_type = pat" >> ~/.databrickscfg
              echo "token = $(DATABRICKS-TOKEN)" >> ~/.databrickscfg

              # Deploy bundle
              databricks bundle deploy --profile DEFAULT -t $(environment)
            displayName: 'Install & Deploy Databricks Asset Bundle'
            